### ISSUE TITLE
The .NET 11 unit gate does not build: SYSLIB0066 in RaskDatabaseProviderTests

### ISSUE THREAD

**Issue by pal-tamas** [pal-tamas/rask#1103]
`scripts/run-unit-net11-local.sh` (the ".NET 11 unit" gate in `run-all-gates.sh`) fails at the build, on `origin/main`:

```
tests/Rask.Tests/RaskDatabaseProviderTests.cs(254,89): error SYSLIB0066: 'IStartupValidator' is obsolete: 'Implement IAsyncStartupValidator instead.'
```

`The_provider_mismatch_is_the_first_thing_start_up_reports` resolves `IStartupValidator` to trigger start-up validation. .NET 11 obsoletes the interface, and the build is warnings-as-errors, so the whole .NET 11 unit run stops before a single test. The .NET 10 run is unaffected, which is why the pre-commit / pre-push gates (which build .NET 10) stay green.

Introduced by 5e53b681 (Rask:Database:Provider). Found while running every gate for the live-transport branch; not related to it.

Fix: suppress SYSLIB0066 on that one call, with the reason stated — the interface is what `WebApplication` still runs on both target frameworks, and `IAsyncStartupValidator` does not exist on .NET 10, which this test project also builds for.
