### ISSUE TITLE
main does not compile: ChromeScreen still overrides Route/Parent after #756 dropped them

### ISSUE THREAD

**Issue by pal-tamas** [pal-tamas/rask#760]
## What

`origin/main` does not build. `samples/Rask.Example.Shared/Features/Chrome/ChromeScreen.cs` still declares

```csharp
protected override string Route => "chrome";

protected override Type? Parent => typeof(ShowcaseLayout);
```

but #756 (`refactor(routing)!: declare routes with [Route] again and drop the Page base class`) removed
those members — `src/Rask.Core/Routing/Page.cs` no longer exists, and `Screen` now derives from
`Component` with no `Route`/`Parent` to override. Its own doc comment already shows the new form
(`[Route("/todos")]`).

```
samples/Rask.Example.Shared/Features/Chrome/ChromeScreen.cs(22,31): error CS0115: 'ChromeScreen.Route': no suitable method found to override
samples/Rask.Example.Shared/Features/Chrome/ChromeScreen.cs(24,30): error CS0115: 'ChromeScreen.Parent': no suitable method found to override
```

Reproduce on a clean checkout of main:

```bash
dotnet build Rask.slnx -warnaserror -m:1 -p:RaskWasm=false -p:WasmBuildNative=false
```

`Rask.Example.Shared` is referenced by all three showcase hosts, so the failure takes the samples — and
therefore the E2E gate, and any branch's pre-push hook — down with it.

## Why nothing caught it

The classic two-green-PRs-one-red-merge: #754 added `ChromeScreen` using the old API and #756 removed
that API. Each was green on its own base and neither re-ran after the other landed. Tests run locally,
not in CI, so nothing rebuilt the merge result.

## Fix

The mechanical migration, matching the sibling `TablePage`:

```csharp
[Route("chrome")]
[ParentRoute(typeof(ShowcaseLayout))]
public sealed partial class ChromeScreen : Screen
```

Two lines, one file — I have it applied and building green as a separate commit on the #751 branch
(PR #759), since that branch's gate could not run until main compiled. Happy to split it into its own PR
if you would rather land it independently.

Found while rebasing #759 onto main.

**Comment by pal-tamas** [comment]
Fixed on main by #761 and #762, which landed the same migration (`[Route("chrome")]` + `[ParentRoute(typeof(ShowcaseLayout))]`) while this was open. My duplicate commit on the #751 branch was dropped automatically on rebase — git recognised the patch as already upstream.

Verified: main builds clean, and both #759 and #765 were gated on top of it.

Worth noting the shape for next time, since it will recur: neither #754 nor #756 was wrong on its own, and neither was re-run after the other landed. The gates are local and per-branch, so nothing rebuilds the merge result — a merge-queue-style 'rebuild after the base moves' is the only thing that catches this class.
